"""empty message

Revision ID: 26a8b65e8a11
Revises: 06dd27dac200
Create Date: 2021-12-08 09:25:32.130038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a8b65e8a11'
down_revision = '06dd27dac200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendants',
    sa.Column('id_attendant', sa.Integer(), nullable=False),
    sa.Column('nm_attendant', sa.String(length=50), nullable=False),
    sa.Column('nr_cpf', sa.String(length=11), nullable=False),
    sa.Column('nr_telephone', sa.String(length=11), nullable=True),
    sa.Column('nr_cellphone', sa.String(length=11), nullable=True),
    sa.Column('ds_password', sa.String(length=15), nullable=True),
    sa.Column('dt_creation_time', sa.DateTime(), nullable=True),
    sa.Column('id_clinic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_clinic'], ['clinics.id_clinic'], ),
    sa.PrimaryKeyConstraint('id_attendant'),
    sa.UniqueConstraint('nr_cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendants')
    # ### end Alembic commands ###
