"""ds_password column to ds_hash_password

Revision ID: 2b6ac149bd94
Revises: 343bb50832f8
Create Date: 2021-12-13 11:54:00.950700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6ac149bd94'
down_revision = '343bb50832f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendants', sa.Column('ds_hash_password', sa.String(length=255), nullable=True))
    op.alter_column('attendants', 'ds_email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.create_unique_constraint(None, 'attendants', ['ds_email'])
    op.drop_column('attendants', 'ds_password')
    op.add_column('clinics', sa.Column('nr_address', sa.String(length=10), nullable=False))
    op.drop_column('clinics', 'nr_number')
    op.add_column('customers', sa.Column('nr_address', sa.String(length=10), nullable=False))
    op.drop_column('customers', 'nr_number')
    op.add_column('therapists', sa.Column('ds_hash_password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'therapists', ['ds_email'])
    op.drop_column('therapists', 'ds_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapists', sa.Column('ds_password', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'therapists', type_='unique')
    op.drop_column('therapists', 'ds_hash_password')
    op.add_column('customers', sa.Column('nr_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('customers', 'nr_address')
    op.add_column('clinics', sa.Column('nr_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('clinics', 'nr_address')
    op.add_column('attendants', sa.Column('ds_password', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendants', type_='unique')
    op.alter_column('attendants', 'ds_email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_column('attendants', 'ds_hash_password')
    # ### end Alembic commands ###
