"""change table sessions to sessions model, add status column in therapists, rooms

Revision ID: 3331a3c8e4ce
Revises: 06dd27dac200
Create Date: 2021-12-08 11:58:09.673257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3331a3c8e4ce'
down_revision = '06dd27dac200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('id_therapist', sa.Integer(), nullable=True),
    sa.Column('dt_start', sa.DateTime(), nullable=False),
    sa.Column('dt_end', sa.DateTime(), nullable=True),
    sa.Column('ds_status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], ),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], ),
    sa.PrimaryKeyConstraint('id_session')
    )
    op.drop_table('sessions_table')
    op.alter_column('attendants', 'dt_creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('attendants', 'id_clinic',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'attendants', ['nr_cpf'])    
    op.add_column('rooms', sa.Column('ds_status', sa.String(length=15), nullable=True))
    op.add_column('therapists', sa.Column('nr_cellphone', sa.String(length=11), nullable=True))
    op.add_column('therapists', sa.Column('ds_status', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'ds_status')
    op.drop_column('therapists', 'nr_cellphone')
    op.drop_column('rooms', 'ds_status')
    op.add_column('attendants', sa.Column('ds_email', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendants', type_='unique')
    op.alter_column('attendants', 'id_clinic',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendants', 'dt_creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('sessions_table',
    sa.Column('id_session', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_customer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_therapist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dt_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dt_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ds_status', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], name='sessions_table_id_customer_fkey'),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], name='sessions_table_id_therapist_fkey'),
    sa.PrimaryKeyConstraint('id_session', name='sessions_table_pkey')
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###
