"""adding columns nr_number, nr_zip_code in customer, delte ds_comments in customer_records, update birthdate in customer

Revision ID: 343bb50832f8
Revises: 3331a3c8e4ce
Create Date: 2021-12-10 16:43:43.443980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343bb50832f8'
down_revision = '3331a3c8e4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendants', sa.Column('fl_admin', sa.String(length=3), nullable=False))
    op.add_column('customers', sa.Column('nr_number', sa.String(length=10), nullable=False))
    op.add_column('customers', sa.Column('nr_zipcode', sa.String(length=10), nullable=True))
    op.drop_column('customers_records', 'ds_comment')
    op.add_column('techniques', sa.Column('id_therapist', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'techniques', 'therapists', ['id_therapist'], ['id_therapist'])
    op.add_column('therapists', sa.Column('ds_email', sa.String(length=50), nullable=False))
    op.add_column('therapists', sa.Column('fl_admin', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('therapists', 'fl_admin')
    op.drop_column('therapists', 'ds_email')
    op.drop_constraint(None, 'techniques', type_='foreignkey')
    op.drop_column('techniques', 'id_therapist')
    op.add_column('customers_records', sa.Column('ds_comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('customers', 'nr_zipcode')
    op.drop_column('customers', 'nr_number')
    op.drop_column('attendants', 'fl_admin')
    # ### end Alembic commands ###
