"""healthcare not unique

Revision ID: 8e3debcdea3d
Revises: 2b6ac149bd94
Create Date: 2021-12-14 16:25:14.313932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3debcdea3d'
down_revision = '2b6ac149bd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_nr_healthcare_key', 'customers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customers_nr_healthcare_key', 'customers', ['nr_healthcare'])
    # ### end Alembic commands ###
