"""empty message

Revision ID: ce6e43a18ad8
Revises: 343bb50832f8
Create Date: 2021-12-11 17:13:12.210596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e43a18ad8'
down_revision = '343bb50832f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id_clinic', sa.Integer(), nullable=False),
    sa.Column('nm_clinic', sa.String(length=40), nullable=False),
    sa.Column('nr_cnpj', sa.String(length=15), nullable=False),
    sa.Column('ds_address', sa.String(length=30), nullable=False),
    sa.Column('nr_number', sa.String(length=10), nullable=False),
    sa.Column('ds_complement', sa.String(length=20), nullable=True),
    sa.Column('ds_district', sa.String(length=20), nullable=True),
    sa.Column('nr_zipcode', sa.String(length=10), nullable=True),
    sa.Column('ds_city', sa.String(length=30), nullable=True),
    sa.Column('ds_uf', sa.String(length=2), nullable=True),
    sa.Column('ds_email', sa.String(length=30), nullable=True),
    sa.Column('nr_telephone', sa.String(length=11), nullable=True),
    sa.Column('nr_cellphone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id_clinic'),
    sa.UniqueConstraint('ds_email'),
    sa.UniqueConstraint('nr_cnpj')
    )
    op.create_table('customers',
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.Column('nm_customer', sa.String(length=50), nullable=False),
    sa.Column('nr_cpf', sa.String(length=11), nullable=False),
    sa.Column('nr_rg', sa.String(length=11), nullable=True),
    sa.Column('nm_mother', sa.String(length=50), nullable=True),
    sa.Column('nm_father', sa.String(length=50), nullable=True),
    sa.Column('nr_healthcare', sa.String(length=30), nullable=True),
    sa.Column('ds_address', sa.String(length=50), nullable=False),
    sa.Column('nr_number', sa.String(length=10), nullable=False),
    sa.Column('nr_zipcode', sa.String(length=10), nullable=True),
    sa.Column('nr_telephone', sa.String(length=11), nullable=True),
    sa.Column('nr_cellphone', sa.String(length=11), nullable=True),
    sa.Column('ds_email', sa.String(length=50), nullable=True),
    sa.Column('dt_birthdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_customer'),
    sa.UniqueConstraint('nr_cpf'),
    sa.UniqueConstraint('nr_healthcare'),
    sa.UniqueConstraint('nr_rg')
    )
    op.create_table('specialties',
    sa.Column('id_specialty', sa.Integer(), nullable=False),
    sa.Column('nm_specialty', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_specialty'),
    sa.UniqueConstraint('nm_specialty')
    )
    op.create_table('therapists',
    sa.Column('id_therapist', sa.Integer(), nullable=False),
    sa.Column('nm_therapist', sa.String(length=50), nullable=False),
    sa.Column('nr_cpf', sa.String(length=11), nullable=False),
    sa.Column('nr_crm', sa.String(length=15), nullable=True),
    sa.Column('nr_cellphone', sa.String(length=11), nullable=True),
    sa.Column('nm_user', sa.String(length=15), nullable=True),
    sa.Column('ds_status', sa.String(length=15), nullable=True),
    sa.Column('ds_password', sa.String(length=15), nullable=True),
    sa.Column('ds_email', sa.String(length=50), nullable=False),
    sa.Column('fl_admin', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id_therapist'),
    sa.UniqueConstraint('nm_user'),
    sa.UniqueConstraint('nr_cpf'),
    sa.UniqueConstraint('nr_crm')
    )
    op.create_table('attendants',
    sa.Column('id_attendant', sa.Integer(), nullable=False),
    sa.Column('nm_attendant', sa.String(length=50), nullable=False),
    sa.Column('nr_cpf', sa.String(length=11), nullable=False),
    sa.Column('nr_telephone', sa.String(length=11), nullable=True),
    sa.Column('nr_cellphone', sa.String(length=11), nullable=True),
    sa.Column('ds_password', sa.String(length=15), nullable=True),
    sa.Column('ds_email', sa.String(length=40), nullable=True),
    sa.Column('dt_creation_time', sa.DateTime(), nullable=True),
    sa.Column('id_clinic', sa.Integer(), nullable=True),
    sa.Column('fl_admin', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['id_clinic'], ['clinics.id_clinic'], ),
    sa.PrimaryKeyConstraint('id_attendant'),
    sa.UniqueConstraint('nr_cpf')
    )
    op.create_table('customers_records',
    sa.Column('id_customer_record', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], ),
    sa.PrimaryKeyConstraint('id_customer_record')
    )
    op.create_table('rooms',
    sa.Column('id_room', sa.Integer(), nullable=False),
    sa.Column('nm_room', sa.String(length=50), nullable=False),
    sa.Column('ds_status', sa.String(length=15), nullable=True),
    sa.Column('id_specialty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_specialty'], ['specialties.id_specialty'], ),
    sa.PrimaryKeyConstraint('id_room')
    )
    op.create_table('sessions',
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('id_therapist', sa.Integer(), nullable=True),
    sa.Column('dt_start', sa.DateTime(), nullable=False),
    sa.Column('dt_end', sa.DateTime(), nullable=True),
    sa.Column('ds_status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], ),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], ),
    sa.PrimaryKeyConstraint('id_session')
    )
    op.create_table('therapists_specialties',
    sa.Column('id_therapist_specialties', sa.Integer(), nullable=False),
    sa.Column('id_therapist', sa.Integer(), nullable=True),
    sa.Column('id_specialty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_specialty'], ['specialties.id_specialty'], ),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], ),
    sa.PrimaryKeyConstraint('id_therapist_specialties')
    )
    op.create_table('locations',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('dt_start', sa.DateTime(), nullable=False),
    sa.Column('dt_end', sa.DateTime(), nullable=True),
    sa.Column('id_room', sa.Integer(), nullable=True),
    sa.Column('id_clinic', sa.Integer(), nullable=True),
    sa.Column('id_therapist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_clinic'], ['clinics.id_clinic'], ),
    sa.ForeignKeyConstraint(['id_room'], ['rooms.id_room'], ),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], ),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('techniques',
    sa.Column('id_technique', sa.Integer(), nullable=False),
    sa.Column('nm_technique', sa.String(length=50), nullable=False),
    sa.Column('dt_start', sa.Date(), nullable=False),
    sa.Column('dt_end', sa.Date(), nullable=True),
    sa.Column('ds_comment', sa.String(length=1000), nullable=True),
    sa.Column('id_customer_record', sa.Integer(), nullable=False),
    sa.Column('id_therapist', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_customer_record'], ['customers_records.id_customer_record'], ),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], ),
    sa.PrimaryKeyConstraint('id_technique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('techniques')
    op.drop_table('locations')
    op.drop_table('therapists_specialties')
    op.drop_table('sessions')
    op.drop_table('rooms')
    op.drop_table('customers_records')
    op.drop_table('attendants')
    op.drop_table('therapists')
    op.drop_table('specialties')
    op.drop_table('customers')
    op.drop_table('clinics')
    # ### end Alembic commands ###
