"""created sessions

Revision ID: e2e4d07dec8b
Revises: 26a8b65e8a11
Create Date: 2021-12-08 10:29:28.657001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e4d07dec8b'
down_revision = '26a8b65e8a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('id_therapist', sa.Integer(), nullable=True),
    sa.Column('dt_start', sa.DateTime(), nullable=False),
    sa.Column('dt_end', sa.DateTime(), nullable=True),
    sa.Column('ds_status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id_customer'], ),
    sa.ForeignKeyConstraint(['id_therapist'], ['therapists.id_therapist'], ),
    sa.PrimaryKeyConstraint('id_session')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
